// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: logjsontest.proto

package logjson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoLogJsonTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLogJsonTest) Reset() {
	*x = ProtoLogJsonTest{}
	mi := &file_logjsontest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLogJsonTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLogJsonTest) ProtoMessage() {}

func (x *ProtoLogJsonTest) ProtoReflect() protoreflect.Message {
	mi := &file_logjsontest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLogJsonTest.ProtoReflect.Descriptor instead.
func (*ProtoLogJsonTest) Descriptor() ([]byte, []int) {
	return file_logjsontest_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoLogJsonTest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_logjsontest_proto protoreflect.FileDescriptor

const file_logjsontest_proto_rawDesc = "" +
	"\n" +
	"\x11logjsontest.proto\x12\alogjson\x1a\rlogjson.proto\":\n" +
	"\x10ProtoLogJsonTest\x12&\n" +
	"\tuser_name\x18\x01 \x01(\tB\t\xc2\xc2\x1a\x05\n" +
	"\x03md5R\buserNameB-Z+github.com/ethanvc/study/golangproj/logjsonb\x06proto3"

var (
	file_logjsontest_proto_rawDescOnce sync.Once
	file_logjsontest_proto_rawDescData []byte
)

func file_logjsontest_proto_rawDescGZIP() []byte {
	file_logjsontest_proto_rawDescOnce.Do(func() {
		file_logjsontest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logjsontest_proto_rawDesc), len(file_logjsontest_proto_rawDesc)))
	})
	return file_logjsontest_proto_rawDescData
}

var file_logjsontest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logjsontest_proto_goTypes = []any{
	(*ProtoLogJsonTest)(nil), // 0: logjson.ProtoLogJsonTest
}
var file_logjsontest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logjsontest_proto_init() }
func file_logjsontest_proto_init() {
	if File_logjsontest_proto != nil {
		return
	}
	file_logjson_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logjsontest_proto_rawDesc), len(file_logjsontest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logjsontest_proto_goTypes,
		DependencyIndexes: file_logjsontest_proto_depIdxs,
		MessageInfos:      file_logjsontest_proto_msgTypes,
	}.Build()
	File_logjsontest_proto = out.File
	file_logjsontest_proto_goTypes = nil
	file_logjsontest_proto_depIdxs = nil
}
