// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: logjson.proto

package logjson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoLogJson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoLogJson) Reset() {
	*x = ProtoLogJson{}
	mi := &file_logjson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoLogJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLogJson) ProtoMessage() {}

func (x *ProtoLogJson) ProtoReflect() protoreflect.Message {
	mi := &file_logjson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLogJson.ProtoReflect.Descriptor instead.
func (*ProtoLogJson) Descriptor() ([]byte, []int) {
	return file_logjson_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoLogJson) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

var file_logjson_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ProtoLogJson)(nil),
		Field:         54312,
		Name:          "logjson.log_json",
		Tag:           "bytes,54312,opt,name=log_json",
		Filename:      "logjson.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional logjson.ProtoLogJson log_json = 54312;
	E_LogJson = &file_logjson_proto_extTypes[0]
)

var File_logjson_proto protoreflect.FileDescriptor

const file_logjson_proto_rawDesc = "" +
	"\n" +
	"\rlogjson.proto\x12\alogjson\x1a google/protobuf/descriptor.proto\"\"\n" +
	"\fProtoLogJson\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule:Q\n" +
	"\blog_json\x12\x1d.google.protobuf.FieldOptions\x18\xa8\xa8\x03 \x01(\v2\x15.logjson.ProtoLogJsonR\alogJsonB-Z+github.com/ethanvc/study/golangproj/logjsonb\x06proto3"

var (
	file_logjson_proto_rawDescOnce sync.Once
	file_logjson_proto_rawDescData []byte
)

func file_logjson_proto_rawDescGZIP() []byte {
	file_logjson_proto_rawDescOnce.Do(func() {
		file_logjson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logjson_proto_rawDesc), len(file_logjson_proto_rawDesc)))
	})
	return file_logjson_proto_rawDescData
}

var file_logjson_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logjson_proto_goTypes = []any{
	(*ProtoLogJson)(nil),              // 0: logjson.ProtoLogJson
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_logjson_proto_depIdxs = []int32{
	1, // 0: logjson.log_json:extendee -> google.protobuf.FieldOptions
	0, // 1: logjson.log_json:type_name -> logjson.ProtoLogJson
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logjson_proto_init() }
func file_logjson_proto_init() {
	if File_logjson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logjson_proto_rawDesc), len(file_logjson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_logjson_proto_goTypes,
		DependencyIndexes: file_logjson_proto_depIdxs,
		MessageInfos:      file_logjson_proto_msgTypes,
		ExtensionInfos:    file_logjson_proto_extTypes,
	}.Build()
	File_logjson_proto = out.File
	file_logjson_proto_goTypes = nil
	file_logjson_proto_depIdxs = nil
}
