// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.9
// source: golanggrpc.proto

package golanggrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_golanggrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golanggrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_golanggrpc_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_golanggrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_golanggrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_golanggrpc_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoContent) Reset() {
	*x = EchoContent{}
	mi := &file_golanggrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoContent) ProtoMessage() {}

func (x *EchoContent) ProtoReflect() protoreflect.Message {
	mi := &file_golanggrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoContent.ProtoReflect.Descriptor instead.
func (*EchoContent) Descriptor() ([]byte, []int) {
	return file_golanggrpc_proto_rawDescGZIP(), []int{2}
}

func (x *EchoContent) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StructWithData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Value        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructWithData) Reset() {
	*x = StructWithData{}
	mi := &file_golanggrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructWithData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructWithData) ProtoMessage() {}

func (x *StructWithData) ProtoReflect() protoreflect.Message {
	mi := &file_golanggrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructWithData.ProtoReflect.Descriptor instead.
func (*StructWithData) Descriptor() ([]byte, []int) {
	return file_golanggrpc_proto_rawDescGZIP(), []int{3}
}

func (x *StructWithData) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_golanggrpc_proto protoreflect.FileDescriptor

const file_golanggrpc_proto_rawDesc = "" +
	"\n" +
	"\x10golanggrpc.proto\x12\n" +
	"helloworld\x1a\x1cgoogle/protobuf/struct.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1f\n" +
	"\vEchoContent\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"<\n" +
	"\x0eStructWithData\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04data2\xce\x01\n" +
	"\aGreeter\x12>\n" +
	"\bSayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12G\n" +
	"\x11SayHelloReturnNil\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12:\n" +
	"\x04Echo\x12\x17.helloworld.EchoContent\x1a\x17.helloworld.EchoContent\"\x00BU\n" +
	"\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z#github.com/ethanvc/study/golanggrpcb\x06proto3"

var (
	file_golanggrpc_proto_rawDescOnce sync.Once
	file_golanggrpc_proto_rawDescData []byte
)

func file_golanggrpc_proto_rawDescGZIP() []byte {
	file_golanggrpc_proto_rawDescOnce.Do(func() {
		file_golanggrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_golanggrpc_proto_rawDesc), len(file_golanggrpc_proto_rawDesc)))
	})
	return file_golanggrpc_proto_rawDescData
}

var file_golanggrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_golanggrpc_proto_goTypes = []any{
	(*HelloRequest)(nil),   // 0: helloworld.HelloRequest
	(*HelloReply)(nil),     // 1: helloworld.HelloReply
	(*EchoContent)(nil),    // 2: helloworld.EchoContent
	(*StructWithData)(nil), // 3: helloworld.StructWithData
	(*structpb.Value)(nil), // 4: google.protobuf.Value
}
var file_golanggrpc_proto_depIdxs = []int32{
	4, // 0: helloworld.StructWithData.data:type_name -> google.protobuf.Value
	0, // 1: helloworld.Greeter.SayHello:input_type -> helloworld.HelloRequest
	0, // 2: helloworld.Greeter.SayHelloReturnNil:input_type -> helloworld.HelloRequest
	2, // 3: helloworld.Greeter.Echo:input_type -> helloworld.EchoContent
	1, // 4: helloworld.Greeter.SayHello:output_type -> helloworld.HelloReply
	1, // 5: helloworld.Greeter.SayHelloReturnNil:output_type -> helloworld.HelloReply
	2, // 6: helloworld.Greeter.Echo:output_type -> helloworld.EchoContent
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_golanggrpc_proto_init() }
func file_golanggrpc_proto_init() {
	if File_golanggrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_golanggrpc_proto_rawDesc), len(file_golanggrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_golanggrpc_proto_goTypes,
		DependencyIndexes: file_golanggrpc_proto_depIdxs,
		MessageInfos:      file_golanggrpc_proto_msgTypes,
	}.Build()
	File_golanggrpc_proto = out.File
	file_golanggrpc_proto_goTypes = nil
	file_golanggrpc_proto_depIdxs = nil
}
