worker_processes 1;

events {
    worker_connections 1024;
}

http {
    log_format grpc_json escape=json '{"time":"$time_iso8601",'
        '"status":$status,'
        '"upstream":"$upstream_addr",'
        '"uri":"$uri",'
        '"grpc_status":"$upstream_trailer_grpc_status"}';

    server {
        listen 80 http2;

        access_log /var/log/nginx/grpc_access.log grpc_json;
        error_log  /var/log/nginx/grpc_error.log warn;

        location / {
            grpc_pass grpc://host.docker.internal:8231;

            grpc_set_header Host $host;
            grpc_set_header X-Real-IP $remote_addr;
        }
    }
}
