# docker compose up -d
version: '3'

services:
  prometheus:
    image: 'prom/prometheus'
    volumes:
      - './prometheus_config:/etc/prometheus'
    ports:
      - '127.0.0.1:9090:9090'

  # must use datasource: http://prometheus:9090
  grafana:
    # grafana/grafana-enterprise
    # grafana/grafana:7.5.17-ubuntu
    image: grafana/grafana-enterprise
    ports:
      - '127.0.0.1:3000:3000'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '1.0'    # 限制使用 1 个 CPU 核心
          memory: 512M   # 限制使用 512MB 内存
